#!/usr/bin/python
import datetime
import time
def RunTime ():
	start = datetime.datetime.now()
	time.sleep(2)
	end = datetime.datetime.now()
	print "Run Time was: " + str(end-start)
	#print type(end-start)

RunTime()
